############# English navigation ##############

# main menu

[[main]]
name = "Coaching"
url = "/coaching"
weight = 1

[[main]]
name = "Trainings"
url = "/trainings-overview"
weight = 2

[[main]]
parent = "Trainings"
name = "Empathic Leadership"
url = "/trainings/emphatic-leadership"

[[main]]
parent = "Trainings"
name = "Diversity"
url = "/trainings/diversity"

[[main]]
parent = "Trainings"
name = "Priority Management"
url = "/trainings/priority-management"

[[main]]
name = "Workshops"
url = "/workshops-overview"
weight = 3

[[main]]
parent = "Workshops"
name = "Communication"
url = "/workshops/communication"

[[main]]
parent = "Workshops"
name = "Confidence"
url = "/workshops/confidence"

[[main]]
parent = "Workshops"
name = "Time Management"
url = "/workshops/time-management"

[[main]]
name = "About"
url = "/about"
weight = 4




# footer menu
[[footer]]
name = "Imprint"
url = "/imprint"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 2

[[footer]]
name = "About"
url = "/about"
weight = 3

[[footer]]
name = "Contact"
url = "/contact"
weight = 4
